-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- Resize window using <ctrl> arrow keys
--map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase window height" })
--map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease window height" })
--map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease window width" })
--map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase window width" })

--vim.keymap.set("n", "<leader>tt", ":ToggleTerm direction=float <CR>", { desc = "Open terminal" })
--vim.keymap.set("n", "<leader>tT", ":ToggleTerm direction=horizontal <CR>", { desc = "Open horizontal terminal split" })
